title: Mon blog
author: Modre93
thème: minima
email: zewangnin@gmail.com
description: > # Ceci est un blog juste pour m'amuser.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
